server:
  port: 8880
spring:
  application:
    name: backend-one
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
logging:
  level:
    web: TRACE
    org:
      springframework:
        web: TRACE